"""empty message

Revision ID: 498792ff3977
Revises: 44ae0245386c
Create Date: 2019-12-06 13:51:46.691427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498792ff3977'
down_revision = '44ae0245386c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
