"""empty message

Revision ID: a29040b9efb2
Revises: 5a005b925337
Create Date: 2019-12-13 11:02:13.713562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29040b9efb2'
down_revision = '5a005b925337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'image')
    # ### end Alembic commands ###
